# 不使用配置中心的配置话，将bootstrap.properties中配置spring.profiles.active=local
spring:
  profiles: local
  cloud:
    nacos:
      discovery:
        server-addr: 40.73.77.122:8848
        namespace: 33993f0b-c8e4-4986-9768-fd59c3dd64eb
        group: home-auto-local
    gateway:
      discovery:
        locator:
          enabled: true   #默认服务名转发
          lowerCaseServiceId: true
      routes:    #自定义路由规则
        - id: homeauto_contact_gateway
          uri: lb://homeauto-contact-gateway
          predicates:
            - Path= /test11/**
          filters:
            - StripPrefix=1
        - id: auth  #权限
          uri: lb://homeauto-center-oauth
          order: 0
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  #  zipkin:
  #    base-url: http://127.0.0.1:48810
  #    enabled: true
  #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10，如果不配置，有个默认的百分比的
  #  sleuth:
  #    sampler:
  #      percentage: 0.3
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      uri: mongodb://root:aA123456@40.73.77.122:27017/cloud?authSource=cloud
      #&replicaSet=cloud&slaveOk=true&write=1&readPreference=secondaryPreferred
      connections-per-host: 50
      #每个实例允许链接的最大数
      threads-allowed-to-block-for-connection-multiplier: 50
      # 超时时间
      connect-timeout: 5000
      socket-timeout: 3000
      max-wait-time: 1500
      #控制是否在一个连接时，系统会自动重试
      auto-connect-retry: true
      socket-keep-alive: true
  ## mysql
  datasource:
    url: jdbc:postgresql://172.20.11.204:5434/homeauto?useUnicode=true&characterEncoding=utf8&serverTimeZone=CTT
    username: homeauto
    password: landleaf@123.com
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  ## redis链接
  redis:
    database: 3
    ## 如果是单点的redis，打开以下配置 start
    host: 40.73.77.122
    port: 6380
    ## 单点redis配置结束 end
    password: aA123456
    ## 如果是sentinel，打开以下配置 start
    #    sentinel:
    #      master: mymaster
    #      nodes: [10.0.0.7:26379,10.0.0.7:26380,10.0.0.7:26381]
    ## sentinel配置结束
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1ms
        time-between-eviction-runs: 30000ms
    timeout: 30000ms
  application:
    name: homeauto-center-oauth
mqtt:
  server:
    url: tcp://40.73.77.122:1883
    client-id: homeauto-center-oauth-local

management:
  endpoints:
    web:
      exposure:
        include: '*'

homeauto:
  security:
    oauth2:
      # 存储形式
      storeType: jwt
      # token生成加密
      jwtSigningKey: homeauto
      customerEnableRefreshTime: 86400
      # 应用
      clients[0]:
        clientId: app
        clientSecret: app123
        accessTokenValiditySeconds: 300
        refreshTokenValiditySeconds: 86400
        redirectUris: http://127.0.0.1:10012/test/call/back
      clients[1]:
        clientId: homeauto
        clientSecret: homeauto
        # token失效时间
        accessTokenValiditySeconds: 300
        # 可刷新token有效期
        refreshTokenValiditySeconds: 86400
        redirectUris: http://127.0.0.1:10012/test/call/back
    excluded:
      paths: /swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html/**,/**/login/**,/logout/**,/**/upload/**,/**/refresh/cache/**,/**/test/**,/**/login/**,/**/auth/**
    failure:
      statusParam: code
      msgParam: msg
  token:  #解析header中token
    enable: true




