# 不使用配置中心的配置话，将bootstrap.properties中配置spring.profiles.active=local
spring:
  profiles: local
  cloud:
    nacos:
      discovery:
        server-addr: 40.73.77.122:8848
        namespace: 33993f0b-c8e4-4986-9768-fd59c3dd64eb
        group: home-auto-local
  #  zipkin:
  #    base-url: http://127.0.0.1:48810
  #    enabled: true
  #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10，如果不配置，有个默认的百分比的
  #  sleuth:
  #    sampler:
  #      percentage: 0.3
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      uri: mongodb://root:aA123456@40.73.77.122:27017/cloud?authSource=cloud
      #&replicaSet=cloud&slaveOk=true&write=1&readPreference=secondaryPreferred
      connections-per-host: 50
      #每个实例允许链接的最大数
      threads-allowed-to-block-for-connection-multiplier: 50
      # 超时时间
      connect-timeout: 5000
      socket-timeout: 3000
      max-wait-time: 1500
      #控制是否在一个连接时，系统会自动重试
      auto-connect-retry: true
      socket-keep-alive: true
  ## mysql
  datasource:
    url: jdbc:postgresql://134.175.92.62:5432/home_auto?useUnicode=true&characterEncoding=utf8&serverTimeZone=CTT
    username: test
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  ## redis链接
  redis:
    database: 3
    ## 如果是单点的redis，打开以下配置 start
    host: 40.73.77.122
    port: 6380
    ## 单点redis配置结束 end
    password: aA123456
    ## 如果是sentinel，打开以下配置 start
    #    sentinel:
    #      master: mymaster
    #      nodes: [10.0.0.7:26379,10.0.0.7:26380,10.0.0.7:26381]
    ## sentinel配置结束
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1ms
        time-between-eviction-runs: 30000ms
    timeout: 30000ms
  application:
    name: homeauto-center-device
mqtt:
  server:
    url: tcp://40.73.77.122:1883
    client-id: homeauto-center-device-local

management:
  endpoints:
    web:
      exposure:
        include: '*'
auth:
  login:
    enable: true #登录认证使用
    refresh-token:
      expired: 86400
    logout:
      path: /logout,
    excluded:
      paths: /swagger-resources/**,/webjars/**,/v2/**,/swagger-ui.html/**,/**/login/**,/logout,/**/register/**,/**/verification_code/**,/**/forget_password/**,/**/upload/**,/**/forgetPassword/**,/**/send/**,/**/refresh/cache/**,/**/test/**,/mc/app/msg/msg-advert/**,/app/version/**,/web/api/**
  feign:
    enable: true
    token: #服务间token透传
      enable: false
#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 5000
#        read-timeout: 5000
#      smarthome-uc:
#        connect-timeout: 10000
#        read-timeout: 30000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 5000
  MaxAutoRetries: 3
  OkToRetryOnAllOperations: false

server:
  port: 10010

homeauto:
  token:  #解析header中token
    enable: true
  rocketmq:
    producer:
      #开启生产者配置
      enable: false
      groupName: homeauto-test-p
      namesrvAddr: 49.232.174.101:9876
      maxMessageSize: 4096
      sendMsgTimeout: 30000
      #重发次数
      retryTimesWhenSendFailed: 3
    consumer:
      #开启消费者配置
      enable: false
      #消费组名称请用唯一，默认集群方式会以平均消费方式负载均衡
      groupName: homeauto-test-s
      namesrvAddr: 49.232.174.101:9876
      #topic-tags;topic-tags 多个用";"分隔;topic与tag用"-"分隔
      topics: test-*
      consumeThreadMin: 16
      consumeThreadMax: 32
      #每次获取最大数
      consumeMessageBatchMaxSize: 10
  jg:
    app-key: 1cee39b5c6f19e4712ee0351
    master-secret: d69904ee9107bb93e4ce84f8
    # 登陆注册模板
    #    login:
    #      temp-id: 168680
    #      ttl: 1
    # 重置密码
    #    reset:
    #      temp-id: 168704
    #      ttl: 1
    code:
      redis-key-prefix: sms_code_

      mobile-has-send: 'mobile_has_send:'
      mobile-has-send-ttl: 60

      ip-daily-times-limit: 5
  jpush:
    ios-env: false
  email:
    address: ibsteward@landleaf-tech.com
    pwd: Landleaf@2019
    code:
      redis-key-prefix: email_code_